# Generated by Django 4.2.3 on 2023-09-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='slug_topic',
            field=models.SlugField(blank=True),
        ),
    ]
