# Generated by Django 4.2.3 on 2023-09-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_posts_slug_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='slug_topic',
            field=models.SlugField(default='xxx'),
        ),
    ]
