# Generated by Django 4.2.3 on 2023-09-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_pro_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pro_pic',
            field=models.ImageField(null=True, upload_to='pro_pic/'),
        ),
    ]
