# Generated by Django 4.2.3 on 2023-09-18 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interactions',
            old_name='raitng',
            new_name='rating',
        ),
    ]
